#!/usr/bin/env bash
set -Eeuo pipefail
trap 'status=$?; echo "v0.53 conformance failed at line ${LINENO}: ${BASH_COMMAND}" >&2; exit "$status"' ERR
if [ "$#" -ne 3 ]; then echo "usage: conformance-v0530.sh REPORT_BINARY REPOSITORY_ROOT ARTIFACT_ROOT" >&2; exit 64; fi
binary=$(realpath "$1"); repository=$(realpath "$2"); artifact=$(realpath "$3"); probe=$(mktemp -d); mkdir -p "$probe"; command -v jq >/dev/null; test -x "$binary"; test -s "$artifact/releases/verification.json"
echo "v0.53 conformance: verify 75-cell append-only profile"
jq -e '.schema=="gooo/self-improvement-portfolio/contract/v1" and .profile_id=="self-improvement-portfolio-v1" and .total_cells==75 and .denominator_migration=={from:53,to:75,add:22,retire:0,split:0,append_only:true} and .proof_totals=={FOUNDATION:4,COHERENCE:66,REGRESSION:5} and .indicator_totals=={DRIVER:4,OUTCOME:66,GUARDRAIL:5} and .precedence==["REFUTED","UNKNOWN","CLOSED"] and .policy=={denominator_mutation_during_run:false,status_inference_from_missing_evidence:false,runtime_repository_writes:0,caller_owned_temp_output_only:true,cross_project_required_gates:0,aggregate_percentage:false,aggregate_score:false} and (.cells|length)==75 and ([.cells[-4:][]|{ordinal,id,axis,proof,indicator,activity,evaluator,metric_denominator,release_key}]==[
  {ordinal:72,id:"EVALUATOR_INTEGRITY_PROJECTOR_DURABLE_RELEASE",axis:"EVALUATOR_INTEGRITY_PROJECTOR_DURABLE_RELEASE",proof:"COHERENCE",indicator:"OUTCOME",activity:"AdoptEvaluatorIntegrityProjectorDurableRelease",evaluator:"evaluator-integrity-projector",metric_denominator:1,release_key:"evaluator_integrity_projector_durable_release"},
  {ordinal:73,id:"SEMANTIC_IMPACT_SLICER_DURABLE_RELEASE",axis:"SEMANTIC_IMPACT_SLICER_DURABLE_RELEASE",proof:"COHERENCE",indicator:"OUTCOME",activity:"AdoptSemanticImpactSlicerDurableRelease",evaluator:"semantic-impact-slicer",metric_denominator:1,release_key:"semantic_impact_slicer_durable_release"},
  {ordinal:74,id:"SELF_IMPROVEMENT_CYCLE_DETECTOR_DURABLE_RELEASE",axis:"SELF_IMPROVEMENT_CYCLE_DETECTOR_DURABLE_RELEASE",proof:"COHERENCE",indicator:"OUTCOME",activity:"AdoptSelfImprovementCycleDetectorDurableRelease",evaluator:"self-improvement-cycle-detector",metric_denominator:1,release_key:"self_improvement_cycle_detector_durable_release"},
  {ordinal:75,id:"CLOSED_LOOP_SELF_IMPROVEMENT_USECASE_DURABLE_RELEASE",axis:"CLOSED_LOOP_SELF_IMPROVEMENT_USECASE_DURABLE_RELEASE",proof:"COHERENCE",indicator:"OUTCOME",activity:"AdoptClosedLoopSelfImprovementUsecaseDurableRelease",evaluator:"closed-loop-self-improvement-usecase",metric_denominator:1,release_key:"closed_loop_self_improvement_usecase_durable_release"}
])' "$repository/contracts/self-improvement-portfolio-v1.json" >/dev/null
jq -e '.schema=="gooo/self-improvement-portfolio/assessment/v1" and .profile_id=="self-improvement-portfolio-v1" and (.cells|length)==75 and ([.cells[-4:][]|{cell_id,state,release_key}]==[
  {cell_id:"EVALUATOR_INTEGRITY_PROJECTOR_DURABLE_RELEASE",state:"CLOSED",release_key:"evaluator_integrity_projector_durable_release"},
  {cell_id:"SEMANTIC_IMPACT_SLICER_DURABLE_RELEASE",state:"CLOSED",release_key:"semantic_impact_slicer_durable_release"},
  {cell_id:"SELF_IMPROVEMENT_CYCLE_DETECTOR_DURABLE_RELEASE",state:"CLOSED",release_key:"self_improvement_cycle_detector_durable_release"},
  {cell_id:"CLOSED_LOOP_SELF_IMPROVEMENT_USECASE_DURABLE_RELEASE",state:"CLOSED",release_key:"closed_loop_self_improvement_usecase_durable_release"}
])' "$repository/evidence/assessment-v1.json" >/dev/null
echo "v0.53 conformance: verify 66-lock reuse, four live locks, wave, and product receipts"
jq -e '.schema=="gooo/self-improvement-portfolio/release-verification/v1" and .summary=={total:70,verified:70,unknown:0,refuted:0} and (.releases|length)==70 and .release_lock_snapshot.parent_reuse.reused==66 and .release_lock_snapshot.changed_live.selected==4 and .release_lock_snapshot.changed_live.executed==4 and .release_lock_snapshot.changed_live.live_verified==4 and .release_lock_snapshot.full_70_lock_audit.executed==false' "$artifact/releases/verification.json" >/dev/null
jq -e '.schema=="gooo/self-improvement-ledger/v0530-live-lock-receipt/v1" and .parent_reuse.reused==66 and .parent_reuse.selected==0 and .parent_reuse.executed==0 and .changed_live.selected==4 and .changed_live.executed==4 and .changed_live.live_verified==4 and .changed_live.unknown==0 and .changed_live.refuted==0 and .full_70_lock_audit=={executed:false,required:false}' "$artifact/v0530-live-lock-receipt.json" >/dev/null
jq -e '.schema=="gooo/self-improvement-ledger/atomic-v0530-adoption-wave/v1" and .wave.projected_profile_state=={total:75,closed:72,unknown:1,refuted:2} and .parent_preservation.parent_release=="v0.52.0" and .parent_preservation.parent_reused==66 and .parent_preservation.changed_selected==4 and .parent_preservation.changed_executed==4 and .parent_preservation.full_70_lock_audit==false and .semantic_wave.state=="CLOSED" and .semantic_wave.accepted_wave_order==["proposal-cell-72","proposal-cell-73","proposal-cell-74","proposal-cell-75"] and .authority.verification=="GITHUB_ACTIONS_ONLY"' "$repository/evidence/atomic-v0530-wave-v1.json" >/dev/null
jq -e '.schema=="gooo/self-improvement-ledger/v0530-product-integration/v1" and (.products|length)==4 and .receipts.evaluator_integrity_projector.adoption_state=="CLOSED" and .receipts.semantic_impact_slicer.adoption_state=="CLOSED" and .receipts.self_improvement_cycle_detector.adoption_state=="CLOSED" and .receipts.closed_loop_self_improvement_usecase.adoption_state=="CLOSED" and .claims.general_program_equivalence==false and .claims.whole_language_improvement=="UNKNOWN" and .authority.repository_writes==0' "$artifact/v0530-products/product-integration.json" >/dev/null
echo "v0.53 conformance: generate report through GitHub Actions runtime"
start=$(date +%s%N); /usr/bin/time -f '%M' -o "$probe/report-peak-rss" "$binary" -profile "$repository/contracts/self-improvement-portfolio-v1.json" -activities "$repository/examples/self-improvement-portfolio/main.gooo" -assessment "$repository/evidence/assessment-v1.json" -verification "$artifact/releases/verification.json" -runtime "$artifact/runtime.json" -repository-root "$repository" -artifact-root "$artifact" -output-json "$probe/report.json" -output-markdown "$probe/report.md" 2>"$artifact/report-command.stderr"; end=$(date +%s%N); report_wall=$(( (end-start)/1000000 )); report_raw=$((end-start)); report_rss=$(cat "$probe/report-peak-rss"); jq --argjson wall "$report_wall" --argjson raw "$report_raw" --argjson rss "$report_rss" '.timing.report={wall_ms:$wall,duration_ns:$raw,peak_rss_kib:($rss|tonumber)}' "$artifact/runtime.json" > "$probe/runtime.json"; mv "$probe/runtime.json" "$artifact/runtime.json"
start=$(date +%s%N); /usr/bin/time -f '%M' -o "$probe/final-report-peak-rss" "$binary" -profile "$repository/contracts/self-improvement-portfolio-v1.json" -activities "$repository/examples/self-improvement-portfolio/main.gooo" -assessment "$repository/evidence/assessment-v1.json" -verification "$artifact/releases/verification.json" -runtime "$artifact/runtime.json" -repository-root "$repository" -artifact-root "$artifact" -output-json "$artifact/report.json" -output-markdown "$artifact/report.md" 2>"$artifact/final-report-command.stderr"; end=$(date +%s%N); final_wall=$(( (end-start)/1000000 )); final_raw=$((end-start)); final_rss=$(cat "$probe/final-report-peak-rss")
jq -e '(.schema=="gooo/gooo-self-improvement-portfolio/report/v1" or .schema=="gooo/self-improvement-portfolio/report/v1") and .summary=={total:75,closed:72,unknown:1,refuted:2} and .proof_counts.FOUNDATION.denominator==4 and .proof_counts.COHERENCE.denominator==66 and .proof_counts.REGRESSION.denominator==5 and .indicator_counts.DRIVER.denominator==4 and .indicator_counts.OUTCOME.denominator==66 and .indicator_counts.GUARDRAIL.denominator==5 and .bindings=={one_to_one:true,cells:75,activities:75,unique_axes:75,unique_metrics:75,source_bindings:75,ir_bindings:75,generated_artifact_bindings:75,evaluator_bindings:75} and .releases=={total:70,verified:70,unknown:0,refuted:0} and .precedence==["REFUTED","UNKNOWN","CLOSED"] and .policy.aggregate_percentage==false and .policy.aggregate_score==false and .authority.runtime_repository_writes==0 and .authority.caller_owned_temp_output==true and .authority.cross_project_required_gates==0 and .local_execution_counts=={gofmt:0,build:0,test:0,vet:0,conformance:0} and (has("percentage")|not) and (has("score")|not)' "$artifact/report.json" >/dev/null
jq -S -n --slurpfile report "$artifact/report.json" --argjson wall "$final_wall" --argjson raw "$final_raw" --argjson rss "$final_rss" '{schema:"gooo/self-improvement-portfolio/conformance/v1",tests:{executed:1,reused:0,skipped:0},report_decision:$report[0].decision,summary:$report[0].summary,report_generation:{wall_ms:$wall,duration_ns:$raw,peak_rss_kib:$rss},repository_writes:$report[0].authority.runtime_repository_writes}' > "$artifact/conformance.json"
jq -e '.schema=="gooo/self-improvement-portfolio/conformance/v1" and .summary=={total:75,closed:72,unknown:1,refuted:2} and .repository_writes==0' "$artifact/conformance.json" >/dev/null
jq '{schema,decision,summary,proof_counts,indicator_counts,releases,authority,local_execution_counts}' "$artifact/report.json"
echo "v0.53 conformance passed: total=75 closed=72 unknown=1 refuted=2 releases=70"
