#!/usr/bin/env bash
set -Eeuo pipefail
trap 'status=$?; echo "v0.53 product integration failed at line ${LINENO}: ${BASH_COMMAND}" >&2; exit "$status"' ERR

if [ "$#" -ne 2 ]; then echo "usage: verify-v0530-products.sh ARTIFACT_ROOT REPOSITORY_ROOT" >&2; exit 64; fi
artifact_root=$(realpath "$1"); repository=$(realpath "$2"); products="$artifact_root/v0530-products"; temp_base="${RUNNER_TEMP:-$artifact_root/.v0530-products-temp}"; temp_root="$temp_base/gooo-v0530-products-temp"
rm -rf "$products" "$temp_root"; mkdir -p "$products" "$temp_root"
command -v jq >/dev/null; command -v tar >/dev/null; command -v sha256sum >/dev/null; command -v awk >/dev/null; command -v wc >/dev/null; command -v go >/dev/null; test -n "${GH_TOKEN:-}"
sha256_prefixed() { printf 'sha256:%s\n' "$(sha256sum "$1"|awk '{print $1}')"; }
file_count() { find "$1" -type f -print | wc -l | tr -d ' '; }
file_bytes() { find "$1" -type f -exec wc -c {} + | awk 'END {print $1+0}'; }
lock_json() { jq -c --arg key "$1" '.releases[$key]' "$repository/contracts/release-locks-v1.json"; }
copy_named() { local root=$1 name=$2 dest=$3; local source; source=$(find "$root" -type f -name "$name" -print -quit); test -n "$source"; cp "$source" "$dest"; }

echo "v0.53 products: reconcile evaluator integrity projector v0.1.1"
eval_key=evaluator_integrity_projector_durable_release; eval_lock=$(lock_json "$eval_key"); eval_product="$products/evaluator-integrity"; eval_asset_root="$artifact_root/releases/$eval_key/assets"; mkdir -p "$eval_product"
for name in conformance.json provenance.json replay.json github-run.json SHA256SUMS; do cp "$eval_asset_root/$name" "$eval_product/$name"; done
jq -e '.policy_name=="evaluator_integrity" and .policy_version=="1" and .denominator==12 and .layer_counts=={COHERENCE:4,FOUNDATION:4,REGRESSION:4} and .lens_counts=={DRIVER:4,GUARDRAIL:4,OUTCOME:4} and .generated_artifact_count==2 and .generated_artifacts==["internal/generated/policy.go","internal/generated/fixtures.go"] and .authority_counters=={metacode_authority:1,generated_evaluator_authority:0,runtime_policy_mutations:0,immutable_policy_mutations:0,bounded_amendment_authority:1,human_decision_receipts:12,cross_project_required_gates:0,repository_writes_runtime:0,local_validation_count:0} and .case_counts=={CLOSED:1,FIXED_POINT:1,REFUTED:4,UNKNOWN:6} and .passed==true and .failures==[] and any(.cases[]; .case=="normal" and .decision=="FIXED_POINT" and .improvement=="FIXED_POINT" and (.resolution_events|index("precedence:REFUTED>UNKNOWN>CLOSED"))!=null) and any(.cases[]; .case=="counter_unknown_top_level" and .decision=="UNKNOWN" and (.operational_refuted|index("OPERATIONAL_REFUTED:UNKNOWN_TOP_LEVEL_DECISION_REJECTED"))!=null) and any(.cases[]; .case=="counter_denominator_shrink" and .decision=="REFUTED") and any(.cases[]; .case=="counter_joint_change" and .decision=="REFUTED") and any(.cases[]; .case=="counter_precedence_inversion" and .decision=="REFUTED")' "$eval_product/conformance.json" >/dev/null
jq -e '.github_actions==true and .github_token_source=="github.token" and .generated_artifact_count==2 and .repository_writes_runtime==0 and .local_validation_count==0 and .cross_project_required_gates==0 and .measurement_status=="OBSERVED"' "$eval_product/provenance.json" >/dev/null
jq -e '.policy_name=="evaluator_integrity" and .stable==true and (.cases|length)==12 and all(.cases[]; .stable==true)' "$eval_product/replay.json" >/dev/null
jq -S -n --argjson lock "$eval_lock" --arg asset_digest "$(sha256_prefixed "$eval_asset_root/conformance.json")" --slurpfile conformance "$eval_product/conformance.json" --slurpfile provenance "$eval_product/provenance.json" --slurpfile replay "$eval_product/replay.json" --slurpfile run "$eval_product/github-run.json" '{schema:"gooo/self-improvement-ledger/v0530-evaluator-integrity-receipt/v1",release:$lock,asset_observed_digest:$asset_digest,adoption_state:"CLOSED",released:{conformance:$conformance[0],provenance:$provenance[0],replay:$replay[0],github_run:$run[0]},claims:{denominator_drift:"REFUTED",evaluator_drift:"UNKNOWN",unknown_top_level_not_fixed_point:true,precedence:["REFUTED","UNKNOWN","CLOSED"],general_program_equivalence:false},preservation:{historical_refutations_preserved:true,external_utility:"UNKNOWN"},improvement:{state:"UNKNOWN",reason:"no same-identity before-after pair for the released evaluator was supplied"},authority:{verification:"GITHUB_ACTIONS",repository_writes:0,local_test_executions:0,cross_project_required_gates:0}}' > "$eval_product/receipt.json"

echo "v0.53 products: reconcile semantic impact slicer v0.1.1"
slicer_key=semantic_impact_slicer_durable_release; slicer_lock=$(lock_json "$slicer_key"); slicer_archive="$artifact_root/releases/$slicer_key/assets/gooo-semantic-impact-slicer-v0.1.1.tar.gz"; slicer_temp="$temp_root/slicer"; slicer_product="$products/semantic-impact-slicer"; mkdir -p "$slicer_temp" "$slicer_product"; tar --no-xattrs -xzf "$slicer_archive" -C "$slicer_temp"; slicer_source=$(find "$slicer_temp" -mindepth 1 -maxdepth 1 -type d -print -quit); test -n "$slicer_source"
slicer_bin="$temp_root/gooo-slicer"; (cd "$slicer_source" && go build -trimpath -o "$slicer_bin" ./cmd/gooo-slicer)
"$slicer_bin" conformance --fixtures "$slicer_source/fixtures" > "$slicer_product/conformance.json"; "$slicer_bin" replay --fixtures "$slicer_source/fixtures" > "$slicer_product/replay.json"
jq -e '.mode=="conformance" and .fixture_count==12 and .passed==12 and .failed==0' "$slicer_product/conformance.json" >/dev/null
jq -e '.mode=="replay" and .fixture_count==12 and (.aggregate_sha256|length)==64' "$slicer_product/replay.json" >/dev/null
jq -n '
  def nid: ("n" + (.|tostring|if length==1 then "0"+. else . end));
  def nodes($candidate): [range(1;24) as $i | {id:($i|nid),digest:(if $candidate and $i<=7 then ("candidate-"+($i|nid)) else ("base-"+($i|nid)) end),deps:(if $i>=8 and $i<=18 then ["n01"] else [] end),authority:"auth",provenance:(if $candidate and $i<=7 then "" else ("prov-"+($i|nid)) end),indicator:"OUTCOME"}];
  def lock($i;$id;$check): {id:$id,node_id:($i|nid),check_id:$check,status:"CLOSED",evidence_digest:("ev-"+$id),toolchain:"go1.27.1",evaluator:"eval-1",authority:"auth",provenance:("prov-"+($i|nid))};
  {scenario:"v0530-impact-slice-selection-only",previous:{toolchain:"go1.27.1",evaluator:"eval-1",nodes:nodes(false),locks:([range(1;19) as $i|lock($i;"lock-"+($i|nid);"check-"+($i|nid))]+[range(1;4) as $i|lock($i;"legacy-extra-"+($i|nid);"legacy-extra-"+($i|nid)+"-check")]+[range(19;24) as $i|lock($i;"lock-"+($i|nid);"check-"+($i|nid))]),checks:[]},candidate:{toolchain:"go1.27.1",evaluator:"eval-1",nodes:nodes(true),checks:[range(1;19) as $i|{id:("check-"+($i|nid)),node_id:($i|nid),cell_id:"C05",indicator:"OUTCOME"}]}}' > "$slicer_product/selection-fixture.json"
"$slicer_bin" plan --input "$slicer_product/selection-fixture.json" > "$slicer_product/selection-report.json"
jq -e '.scenario=="v0530-impact-slice-selection-only" and .selection_mode=="selection-only" and .metrics=={semantic_nodes:23,changed_nodes:7,selected_checks:18,reusable_locks:5,invalidated_locks:21,unresolved_nodes:7,executed_checks:0,generated_artifacts:1} and .execution=={mode:"selection-only",cache_hits_are_execution:false} and .performance.status=="UNKNOWN" and (.unresolved|length)==7 and .inventory.conformance_cells==12 and .inventory.activities==12 and .inventory.root_readme_excluded==true and .inventory.cross_project_required_gates==0 and .inventory.local_validation_count==0 and .inventory.runtime_repository_writes==0 and .inventory.temp_output_scope=="caller-owned"' "$slicer_product/selection-report.json" >/dev/null
slicer_source_digest="sha256:$(cd "$slicer_source" && sha256sum gooo/activities.gooo gooo/conformance.gooo gooo/rules.gooo | LC_ALL=C sort | sha256sum | awk '{print $1}')"
slicer_ir_digest="$(sha256_prefixed "$slicer_source/internal/generated/model.gen.go")"
jq -S -n --argjson lock "$slicer_lock" --arg asset_digest "$(sha256_prefixed "$slicer_archive")" --arg source_digest "$slicer_source_digest" --arg ir_digest "$slicer_ir_digest" --slurpfile conformance "$slicer_product/conformance.json" --slurpfile replay "$slicer_product/replay.json" --slurpfile projection "$slicer_product/selection-report.json" '{schema:"gooo/self-improvement-ledger/v0530-semantic-impact-slicer-receipt/v1",release:$lock,asset_observed_digest:$asset_digest,source:{target_commit_sha:"7d9fac1a614a8a35a7578f7bff7800c440da0184",paths:["gooo/activities.gooo","gooo/conformance.gooo","gooo/rules.gooo"],graph_digest:$source_digest},ir:{path:"internal/generated/model.gen.go",digest:$ir_digest},adoption_state:"CLOSED",released:{conformance:$conformance[0],replay:$replay[0]},selection_only_projection:$projection[0],claims:{selection_only:true,cache_hits_are_execution:false,root_readme_excluded:true,performance:"UNKNOWN",general_program_equivalence:false},preservation:{historical_publish_before_policy:"OPERATIONAL_REFUTED",historical_refutations_preserved:true,external_utility:"UNKNOWN"},improvement:{state:"UNKNOWN",reason:"selection-only planning is not a same-scenario before-after improvement claim"},authority:{verification:"GITHUB_ACTIONS",repository_writes:0,local_test_executions:0,cross_project_required_gates:0}}' > "$slicer_product/receipt.json"

echo "v0.53 products: reconcile self-improvement cycle detector v0.1.0"
cycle_key=self_improvement_cycle_detector_durable_release; cycle_lock=$(lock_json "$cycle_key"); cycle_archive="$artifact_root/releases/$cycle_key/assets/gooo-release-report-v0.1.0.tar.gz"; cycle_temp="$temp_root/cycle"; cycle_product="$products/self-improvement-cycle-detector"; mkdir -p "$cycle_temp" "$cycle_product"; tar --no-xattrs -xzf "$cycle_archive" -C "$cycle_temp"; cycle_root=$(find "$cycle_temp" -type f -name conformance-report.json -print -quit | xargs dirname); test -n "$cycle_root"
for name in conformance-report.json replay-report.json authority.json inventory.json runtime-rss.json; do cp "$cycle_root/$name" "$cycle_product/$name"; done
jq -e '.schema=="gooo.trace.conformance.report/v1" and .case_count==12 and .case_counts=={CLOSED:2,UNKNOWN:8,REFUTED:2} and .decision_counts=={CLOSED:46,UNKNOWN:96,REFUTED:2} and any(.cases[]; .name=="explicit-fixed-point" and .case_decision=="CLOSED" and .periods==[1] and .detection_kinds==["EXPLICIT_FIXED_POINT"]) and any(.cases[]; .name=="repeated-no-op" and .case_decision=="UNKNOWN" and .periods==[1]) and any(.cases[]; .name=="period-2-oscillation" and .case_decision=="UNKNOWN" and .periods==[2]) and any(.cases[]; .name=="period-n-cycle" and .case_decision=="UNKNOWN" and .periods==[3]) and any(.cases[]; .name=="evaluator-drift" and .case_decision=="UNKNOWN") and any(.cases[]; .name=="missing-state" and .case_decision=="UNKNOWN") and any(.cases[]; .name=="stale-evidence" and .case_decision=="UNKNOWN") and any(.cases[]; .name=="ambiguous-ordering" and .case_decision=="UNKNOWN") and any(.cases[]; .name=="regression" and .case_decision=="REFUTED") and any(.cases[]; .name=="counterexample-recurrence" and .case_decision=="REFUTED")' "$cycle_product/conformance-report.json" >/dev/null
jq -e '.schema=="gooo.trace.semantic-progress" and .activity_count==12 and .cell_count==12 and .proof_choice_counts=={COHERENCE:4,FOUNDATION:4,REGRESSION:4} and .indicator_counts=={DRIVER:4,GUARDRAIL:4,OUTCOME:4} and .no_global_score==true' "$cycle_product/authority.json" >/dev/null
jq -e '.included_file_count==30 and .excluded_files==["README.md"] and .authority_files==[".gooo/semantics.gooo"] and .generated_files==["internal/generated/detector_gen.go","internal/generated/doc.go"]' "$cycle_product/inventory.json" >/dev/null
jq -e '.schema=="gooo.trace.replay.report/v1" and .case_count==12 and .deterministic==true and .first_digest==.second_digest' "$cycle_product/replay-report.json" >/dev/null
jq -e '.repository_writes==0' "$cycle_product/runtime-rss.json" >/dev/null
jq -S -n --argjson lock "$cycle_lock" --arg asset_digest "$(sha256_prefixed "$cycle_archive")" --slurpfile conformance "$cycle_product/conformance-report.json" --slurpfile authority "$cycle_product/authority.json" --slurpfile inventory "$cycle_product/inventory.json" --slurpfile replay "$cycle_product/replay-report.json" --slurpfile runtime "$cycle_product/runtime-rss.json" '{schema:"gooo/self-improvement-ledger/v0530-cycle-detector-receipt/v1",release:$lock,asset_observed_digest:$asset_digest,adoption_state:"CLOSED",released:{conformance:$conformance[0],authority:$authority[0],inventory:$inventory[0],replay:$replay[0],runtime:$runtime[0]},claims:{periods:[1,2,3],evaluator_frontier:"UNKNOWN",missing_frontier:"UNKNOWN",stale_frontier:"UNKNOWN",ordering_frontier:"UNKNOWN",no_global_score:true},preservation:{direct_main_history:"OPERATIONAL_REFUTED",failed_release_history:"OPERATIONAL_REFUTED",historical_refutations_preserved:true,external_utility:"UNKNOWN"},improvement:{state:"UNKNOWN",reason:"cycle detection is not a same-scenario before-after improvement claim"},authority:{verification:"GITHUB_ACTIONS",repository_writes:0,local_test_executions:0,cross_project_required_gates:0}}' > "$cycle_product/receipt.json"

echo "v0.53 products: reconcile closed-loop self-improvement use case v0.1.3"
usecase_key=closed_loop_self_improvement_usecase_durable_release; usecase_lock=$(lock_json "$usecase_key"); usecase_archive="$artifact_root/releases/$usecase_key/assets/v0.1.3.tar.gz"; usecase_temp="$temp_root/usecase"; usecase_product="$products/closed-loop-usecase"; mkdir -p "$usecase_temp" "$usecase_product"; tar --no-xattrs -xzf "$usecase_archive" -C "$usecase_temp"; usecase_root=$(find "$usecase_temp" -type f -name conformance-report.json -print -quit | xargs dirname); test -n "$usecase_root"
for name in conformance-report.json artifact-manifest.json human-adoption-boundary.json measurement-receipt.json replay-receipt.json before-after-comparison.json baseline-evidence.json candidate-evidence.json minimized-counterexample.json upstream-verification.json; do cp "$usecase_root/$name" "$usecase_product/$name"; done
jq -e '.schema=="gooo/conformance-report/v1" and .decision=="CLOSED" and .denominator==12 and .activity_count==12 and .proof_distribution=={COHERENCE:4,FOUNDATION:4,REGRESSION:4} and .indicator_distribution=={DRIVER:4,GUARDRAIL:4,OUTCOME:4} and .case_resolution_distribution=={CLOSED:4,UNKNOWN:4,REFUTED:4} and .passed_case_count==12 and .generated_artifact_count==7 and .evidence_artifact_count==10 and .runtime_evaluation_artifact_count==25 and .total_caller_owned_artifact_count==42 and .authority_counters=={cross_project_required_gates:0,local_test_executions:0,repository_writes:0} and .resolution_precedence==["REFUTED","UNKNOWN","CLOSED"] and .human_adoption_boundary.status=="UNKNOWN" and .human_adoption_boundary.automatic_apply_authority==0' "$usecase_product/conformance-report.json" >/dev/null
jq -e '.schema=="gooo/caller-owned-artifact-manifest/v1" and .artifact_count==10 and .evidence_artifact_count==10 and .generator_artifact_count==7 and .runtime_evaluation_artifact_count==25 and .repository_writes==0' "$usecase_product/artifact-manifest.json" >/dev/null
jq -e '.schema=="gooo/human-adoption-boundary/v1" and .status=="UNKNOWN" and .automatic_apply_authority==0 and .repository_writes==0 and .unknown.unknown_class=="HUMAN_ADOPTION_REQUIRED"' "$usecase_product/human-adoption-boundary.json" >/dev/null
jq -e '.schema=="gooo/before-after-comparison/v1" and .status=="CLOSED" and .semantic_correctness_delta=="CHANGED: CLOSED/FIXED_POINT -> UNKNOWN/FEEDBACK_COVERAGE_DECISION_UNKNOWN" and .identical_context.evaluator_identity=="feedback-coverage-decision-evaluator@v0.1.0" and .performance_memory_claim.status=="UNKNOWN" and .repository_writes==0' "$usecase_product/before-after-comparison.json" >/dev/null
jq -e '.schema=="gooo/measurement-receipt/v1" and .before=={peak_rss_kib:27484,wall_ms:40} and .after=={peak_rss_kib:27460,wall_ms:50} and .performance_memory_claim.status=="UNKNOWN" and .repository_writes==0' "$usecase_product/measurement-receipt.json" >/dev/null
jq -e '.schema=="gooo/replay-receipt/v1" and .stable==true and .replay_count==2 and .local_test_executions==0 and .repository_writes==0 and .cross_project_required_gates==0' "$usecase_product/replay-receipt.json" >/dev/null
jq -e '.schema=="gooo/upstream-verification/v1" and .verified_count==5' "$usecase_product/upstream-verification.json" >/dev/null
jq -S -n --argjson lock "$usecase_lock" --arg asset_digest "$(sha256_prefixed "$usecase_archive")" --slurpfile conformance "$usecase_product/conformance-report.json" --slurpfile manifest "$usecase_product/artifact-manifest.json" --slurpfile boundary "$usecase_product/human-adoption-boundary.json" --slurpfile measurement "$usecase_product/measurement-receipt.json" --slurpfile replay "$usecase_product/replay-receipt.json" --slurpfile comparison "$usecase_product/before-after-comparison.json" --slurpfile candidate "$usecase_product/candidate-evidence.json" '{schema:"gooo/self-improvement-ledger/v0530-closed-loop-usecase-receipt/v1",release:$lock,asset_observed_digest:$asset_digest,adoption_state:"CLOSED",released:{conformance:$conformance[0],artifact_manifest:$manifest[0],human_adoption_boundary:$boundary[0],measurement:$measurement[0],replay:$replay[0],before_after:$comparison[0],candidate_evidence:$candidate[0]},claims:{before_after_semantic_delta:"CHANGED: CLOSED/FIXED_POINT -> UNKNOWN/FEEDBACK_COVERAGE_DECISION_UNKNOWN",same_identity:true,performance:"UNKNOWN",human_adoption:"UNKNOWN",external_utility:"UNKNOWN",general_program_equivalence:false},preservation:{direct_main_history:"OPERATIONAL_REFUTED",mutable_release_history:"OPERATIONAL_REFUTED",historical_refutations_preserved:true},improvement:{state:"UNKNOWN",reason:"performance and external utility remain unpaired or human-gated"},authority:{verification:"GITHUB_ACTIONS",repository_writes:0,local_test_executions:0,cross_project_required_gates:0}}' > "$usecase_product/receipt.json"

echo "v0.53 products: emit candidate-only packaging measurements"
candidate="$temp_root/candidate-package"; mkdir -p "$candidate"; cp -a "$products/." "$candidate/"; cp "$repository/contracts/release-locks-v1.json" "$candidate/release-locks-v1.json"; cp "$repository/contracts/self-improvement-portfolio-v1.json" "$candidate/self-improvement-portfolio-v1.json"; package="$temp_root/v0530-candidate-package.tar.gz"; start=$(date +%s%N); /usr/bin/time -f '%M' -o "$temp_root/candidate-peak-rss" tar --no-xattrs -czf "$package" -C "$candidate" .; end=$(date +%s%N); wall=$(( (end-start)/1000000 )); if [ "$wall" -lt 1 ]; then wall=1; fi
jq -S -n --argjson files "$(file_count "$candidate")" --argjson bytes "$(file_bytes "$candidate")" --argjson wall "$wall" --argjson rss "$(cat "$temp_root/candidate-peak-rss")" '{schema:"gooo/self-improvement-ledger/v0530-packaging-receipt/v1",candidate_only:true,baseline_published:false,candidate:{files:$files,bytes:$bytes,wall_ms:$wall,peak_rss_kib:$rss},baseline:{files:null,bytes:null,wall_ms:null,peak_rss_kib:null},improvement:{state:"UNKNOWN",reason:"no exact immutable v0.52-to-v0.53 package before-after pair is published"},authority:{verification:"GITHUB_ACTIONS",repository_writes:0,local_test_executions:0,cross_project_required_gates:0}}' > "$products/packaging-receipt.json"
jq -S -n --argjson eval "$eval_lock" --argjson slicer "$slicer_lock" --argjson cycle "$cycle_lock" --argjson usecase "$usecase_lock" --slurpfile eval_receipt "$eval_product/receipt.json" --slurpfile slicer_receipt "$slicer_product/receipt.json" --slurpfile cycle_receipt "$cycle_product/receipt.json" --slurpfile usecase_receipt "$usecase_product/receipt.json" --slurpfile packaging "$products/packaging-receipt.json" '{schema:"gooo/self-improvement-ledger/v0530-product-integration/v1",products:{evaluator_integrity_projector:$eval,semantic_impact_slicer:$slicer,self_improvement_cycle_detector:$cycle,closed_loop_self_improvement_usecase:$usecase},receipts:{evaluator_integrity_projector:$eval_receipt[0],semantic_impact_slicer:$slicer_receipt[0],self_improvement_cycle_detector:$cycle_receipt[0],closed_loop_self_improvement_usecase:$usecase_receipt[0],packaging:$packaging[0]},claims:{general_program_equivalence:false,aggregate_percentage:false,aggregate_score:false,whole_language_improvement:"UNKNOWN",external_utility:"UNKNOWN",candidate_release_immutable:false},authority:{verification:"GITHUB_ACTIONS",repository_writes:0,cross_project_required_gates:0}}' > "$products/product-integration.json"
jq -e '.schema=="gooo/self-improvement-ledger/v0530-product-integration/v1" and (.products|length)==4 and .receipts.evaluator_integrity_projector.adoption_state=="CLOSED" and .receipts.semantic_impact_slicer.adoption_state=="CLOSED" and .receipts.self_improvement_cycle_detector.adoption_state=="CLOSED" and .receipts.closed_loop_self_improvement_usecase.adoption_state=="CLOSED" and .claims.general_program_equivalence==false and .claims.whole_language_improvement=="UNKNOWN" and .claims.external_utility=="UNKNOWN" and .authority.repository_writes==0' "$products/product-integration.json" >/dev/null
echo "v0.53 product integration passed: four immutable upstream receipts, selection-only slicing, cycle-frontier preservation, and closed-loop boundaries"
